# Generated by Django 3.0.1 on 2019-12-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_cost', models.IntegerField()),
                ('product_class', models.CharField(max_length=100)),
                ('no_of_product', models.CharField(max_length=100)),
                ('manufacturare_date', models.DateField(max_length=100)),
                ('expirydate', models.DateField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=100)),
            ],
        ),
    ]
